import { Octokit } from "@octokit/rest"
import _sodium from "libsodium-wrappers"

export type StagingRepo = {
  owner: string
  name: string
  url: string
  defaultBranch: string
}

function botToken(): string {
  const token = process.env.GITHUB_BOT_TOKEN
  if (!token) throw new Error("GITHUB_BOT_TOKEN is not set")
  return token
}

function botOrg(): string {
  const org = process.env.GITHUB_BOT_ORG
  if (!org) throw new Error("GITHUB_BOT_ORG is not set")
  return org
}

function client(): Octokit {
  return new Octokit({ auth: botToken() })
}


export async function repoExists(name: string): Promise<boolean> {
  const octokit = client()
  try {
    await octokit.repos.get({ owner: botOrg(), repo: name })
    return true
  } catch (err: unknown) {
    if (typeof err === "object" && err && "status" in err && (err as { status: number }).status === 404) {
      return false
    }
    throw err
  }
}

export async function createStagingRepo(name: string, description?: string): Promise<StagingRepo> {
  const octokit = client()
  const org = botOrg()

  // auto_init: true creates a stub README + initial commit. This is required because
  // GitHub's Git Data API (createBlob etc) refuses with 409 "Git Repository is empty"
  // on a repo with no commits/ref. Our first real commit will be a child of the auto-init.
  const { data } = await octokit.repos.createInOrg({
    org,
    name,
    description: description ?? "Generated by CLICreator",
    private: false,
    auto_init: true,
    has_issues: false,
    has_projects: false,
    has_wiki: false,
  })

  return {
    owner: data.owner.login,
    name: data.name,
    url: data.html_url,
    defaultBranch: data.default_branch ?? "main",
  }
}

// pushInitialCommit pushes the generated source as a single commit on top of the
// auto-init README commit. Uses inline `content` in createTree (one API call) instead
// of individual createBlob calls — eliminates the secondary rate limit fan-out entirely.
export async function pushInitialCommit(
  owner: string,
  repo: string,
  files: Map<string, Buffer>,
  message: string,
  branch: string = "main"
): Promise<string> {
  const octokit = client()

  // 1. Get the auto-init commit SHA — our new commit's parent
  const { data: ref } = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${branch}`,
  })
  const parentSha = ref.object.sha

  // 2. Create a tree with inline file content — GitHub creates the blobs internally.
  //    One POST instead of N, completely avoids secondary rate limits.
  const { data: tree } = await octokit.git.createTree({
    owner,
    repo,
    tree: Array.from(files.entries()).map(([path, content]) => ({
      path,
      mode: "100644" as const,
      type: "blob" as const,
      content: content.toString("utf-8"),
    })),
  })

  // 3. Create a commit on top of the auto-init commit
  const { data: commit } = await octokit.git.createCommit({
    owner,
    repo,
    message,
    tree: tree.sha,
    parents: [parentSha],
  })

  // 4. Fast-forward the branch to our new commit
  await octokit.git.updateRef({
    owner,
    repo,
    ref: `heads/${branch}`,
    sha: commit.sha,
  })

  return commit.sha
}

// pushCommit creates a new commit on top of an existing parent (the previous build's
// commit). The new tree is fresh — files not in the map are dropped. Returns the new
// commit SHA. Use this for rebuilds; use pushInitialCommit for the very first push.
export async function pushCommit(
  owner: string,
  repo: string,
  files: Map<string, Buffer>,
  _parentSha: string,
  message: string,
  branch: string = "main"
): Promise<string> {
  const octokit = client()

  // Always fetch the live HEAD rather than trusting the stored SHA — the two
  // can drift if a previous release attempt partially committed to the repo.
  const { data: ref } = await octokit.git.getRef({ owner, repo, ref: `heads/${branch}` })
  const parentSha = ref.object.sha

  // Inline content in createTree — one POST instead of N createBlob calls.
  const { data: tree } = await octokit.git.createTree({
    owner,
    repo,
    tree: Array.from(files.entries()).map(([path, content]) => ({
      path,
      mode: "100644" as const,
      type: "blob" as const,
      content: content.toString("utf-8"),
    })),
  })

  const { data: commit } = await octokit.git.createCommit({
    owner,
    repo,
    message,
    tree: tree.sha,
    parents: [parentSha],
  })

  await octokit.git.updateRef({
    owner,
    repo,
    ref: `heads/${branch}`,
    sha: commit.sha,
  })

  return commit.sha
}

export async function inviteCollaborator(
  owner: string,
  repo: string,
  username: string,
  permission: "pull" | "push" | "admin" | "maintain" | "triage" = "push"
): Promise<void> {
  const octokit = client()
  await octokit.repos.addCollaborator({
    owner,
    repo,
    username,
    permission,
  })
}

// Encrypts secretValue with the repo's libsodium public key and stores it as a
// GitHub Actions secret. The bot token needs the `secrets` scope on the repo.
export async function setRepoSecret(
  owner: string,
  repo: string,
  secretName: string,
  secretValue: string,
): Promise<void> {
  const octokit = client()

  const { data: key } = await octokit.actions.getRepoPublicKey({ owner, repo })

  await _sodium.ready
  const binKey = _sodium.from_base64(key.key, _sodium.base64_variants.ORIGINAL)
  const binSec = _sodium.from_string(secretValue)
  const encBytes = _sodium.crypto_box_seal(binSec, binKey)
  const encryptedValue = _sodium.to_base64(encBytes, _sodium.base64_variants.ORIGINAL)

  await octokit.actions.createOrUpdateRepoSecret({
    owner,
    repo,
    secret_name: secretName,
    encrypted_value: encryptedValue,
    key_id: key.key_id,
  })
}

// validateRepoName enforces GitHub repo name rules: alphanumeric, dot, dash, underscore.
// Max 100 chars, can't start with a dot or dash.
export function validateRepoName(name: string): string | null {
  if (!name) return "Project name is required"
  if (name.length > 100) return "Project name must be 100 characters or fewer"
  if (!/^[a-zA-Z0-9][a-zA-Z0-9._-]*$/.test(name)) {
    return "Project name can only contain letters, numbers, dots, dashes, and underscores"
  }
  return null
}
