import { Octokit } from "@octokit/rest"
import { createHash } from "crypto"

function botToken(): string {
  const token = process.env.GITHUB_BOT_TOKEN
  if (!token) throw new Error("GITHUB_BOT_TOKEN is not set")
  return token
}

function client(): Octokit {
  return new Octokit({ auth: botToken() })
}

export function computeSha256(buf: Buffer): string {
  return createHash("sha256").update(buf).digest("hex")
}

export type AssetMeta = { downloadUrl: string; sha256: string }

// Creates a GitHub release tagged v{version} and uploads all binaries as assets.
// Returns the release page URL and per-asset download URLs + SHA256s.
export async function createGithubRelease(
  owner: string,
  repo: string,
  cliName: string,
  version: string,
  binaries: Map<string, Buffer>,
): Promise<{ releaseUrl: string; assets: Map<string, AssetMeta> }> {
  const octokit = client()

  const { data: release } = await octokit.repos.createRelease({
    owner,
    repo,
    tag_name: `v${version}`,
    name: `v${version}`,
    body: `Release v${version} of ${cliName} — generated by petl`,
    draft: false,
    prerelease: false,
  })

  const assets = new Map<string, AssetMeta>()
  const uploadBase = release.upload_url.replace(/\{.*?\}$/, "")

  for (const [filename, buf] of binaries) {
    const sha256 = computeSha256(buf)

    const uploadRes = await fetch(`${uploadBase}?name=${encodeURIComponent(filename)}`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${botToken()}`,
        "Content-Type": "application/octet-stream",
        "Content-Length": buf.byteLength.toString(),
      },
      body: new Blob([buf], { type: "application/octet-stream" }),
    })

    if (!uploadRes.ok) {
      const text = await uploadRes.text()
      throw new Error(`Failed to upload ${filename}: ${text}`)
    }

    const data = (await uploadRes.json()) as { browser_download_url: string }
    assets.set(filename, { downloadUrl: data.browser_download_url, sha256 })
  }

  return { releaseUrl: release.html_url, assets }
}

// Converts "my-cli" → "MyCli" for the Homebrew class name.
function toClassName(name: string): string {
  return name
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("")
}

export function generateHomebrewFormula(
  cliName: string,
  version: string,
  repoUrl: string,
  assets: Map<string, AssetMeta>,
): string {
  const get = (platform: string) => assets.get(`${cliName}-${platform}`)

  const darwinArm = get("darwin-arm64")
  const darwinAmd = get("darwin-amd64")
  const linuxArm  = get("linux-arm64")
  const linuxAmd  = get("linux-amd64")

  const lines: string[] = [
    `class ${toClassName(cliName)} < Formula`,
    `  desc "Generated CLI — ${cliName}"`,
    `  homepage "${repoUrl}"`,
    `  version "${version}"`,
    ``,
  ]

  if (darwinArm || darwinAmd) {
    lines.push(`  on_macos do`)
    if (darwinArm) {
      lines.push(`    on_arm do`)
      lines.push(`      url "${darwinArm.downloadUrl}"`)
      lines.push(`      sha256 "${darwinArm.sha256}"`)
      lines.push(`    end`)
    }
    if (darwinAmd) {
      lines.push(`    on_intel do`)
      lines.push(`      url "${darwinAmd.downloadUrl}"`)
      lines.push(`      sha256 "${darwinAmd.sha256}"`)
      lines.push(`    end`)
    }
    lines.push(`  end`)
    lines.push(``)
  }

  if (linuxArm || linuxAmd) {
    lines.push(`  on_linux do`)
    if (linuxArm) {
      lines.push(`    on_arm do`)
      lines.push(`      url "${linuxArm.downloadUrl}"`)
      lines.push(`      sha256 "${linuxArm.sha256}"`)
      lines.push(`    end`)
    }
    if (linuxAmd) {
      lines.push(`    on_intel do`)
      lines.push(`      url "${linuxAmd.downloadUrl}"`)
      lines.push(`      sha256 "${linuxAmd.sha256}"`)
      lines.push(`    end`)
    }
    lines.push(`  end`)
    lines.push(``)
  }

  lines.push(`  def install`)
  lines.push(`    binary = Dir["${cliName}-*"].first || Dir["*"].first`)
  lines.push(`    chmod 0755, binary`)
  lines.push(`    bin.install binary => "${cliName}"`)
  lines.push(`  end`)
  lines.push(``)
  lines.push(`  test do`)
  lines.push(`    system "\#{bin}/${cliName}", "--version"`)
  lines.push(`  end`)
  lines.push(`end`)

  return lines.join("\n")
}

// Generates a portable shell install script that auto-detects OS/arch and
// downloads the right binary from the repo's latest GitHub Release.
export function generateInstallScript(cliName: string, owner: string, repo: string): string {
  return `#!/bin/sh
set -e

CLI_NAME="${cliName}"
OWNER="${owner}"
REPO="${repo}"

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)

case "$ARCH" in
  x86_64)          ARCH="amd64" ;;
  aarch64 | arm64) ARCH="arm64" ;;
  *) echo "Unsupported architecture: $ARCH" >&2; exit 1 ;;
esac

case "$OS" in
  darwin | linux) ;;
  *) echo "Unsupported OS: $OS" >&2; exit 1 ;;
esac

FILENAME="\${CLI_NAME}-\${OS}-\${ARCH}"
URL="https://github.com/\${OWNER}/\${REPO}/releases/latest/download/\${FILENAME}"

echo "Downloading \${CLI_NAME} for \${OS}/\${ARCH}..."
curl -fsSL "\$URL" -o "/tmp/\${CLI_NAME}"
chmod +x "/tmp/\${CLI_NAME}"

INSTALL_DIR="/usr/local/bin"
if [ -w "\$INSTALL_DIR" ]; then
  mv "/tmp/\${CLI_NAME}" "\${INSTALL_DIR}/\${CLI_NAME}"
else
  sudo mv "/tmp/\${CLI_NAME}" "\${INSTALL_DIR}/\${CLI_NAME}"
fi

echo "\${CLI_NAME} installed to \${INSTALL_DIR}/\${CLI_NAME}"
`
}

// Commits (or updates) the formula file in the shared Homebrew tap repo.
// Requires HOMEBREW_TAP_OWNER and HOMEBREW_TAP_REPO env vars.
export async function commitHomebrewFormula(
  cliName: string,
  formulaContent: string,
  version: string,
): Promise<string> {
  const tapOwner = process.env.HOMEBREW_TAP_OWNER
  const tapRepo  = process.env.HOMEBREW_TAP_REPO
  if (!tapOwner || !tapRepo) throw new Error("HOMEBREW_TAP_OWNER / HOMEBREW_TAP_REPO not configured")

  const octokit = client()
  const path = `Formula/${cliName}.rb`

  let existingSha: string | undefined
  try {
    const { data } = await octokit.repos.getContent({ owner: tapOwner, repo: tapRepo, path })
    if (!Array.isArray(data) && "sha" in data) existingSha = data.sha
  } catch (err: unknown) {
    if (
      typeof err !== "object" ||
      !err ||
      !("status" in err) ||
      (err as { status: number }).status !== 404
    ) throw err
  }

  const { data } = await octokit.repos.createOrUpdateFileContents({
    owner: tapOwner,
    repo: tapRepo,
    path,
    message: `${cliName}: release v${version}`,
    content: Buffer.from(formulaContent, "utf-8").toString("base64"),
    ...(existingSha ? { sha: existingSha } : {}),
  })

  return (
    data.content?.html_url ??
    `https://github.com/${tapOwner}/${tapRepo}/blob/main/${path}`
  )
}
