import { Octokit } from "@octokit/rest"

export type StagingRepo = {
  owner: string
  name: string
  url: string
  defaultBranch: string
}

function botToken(): string {
  const token = process.env.GITHUB_BOT_TOKEN
  if (!token) throw new Error("GITHUB_BOT_TOKEN is not set")
  return token
}

function botOrg(): string {
  const org = process.env.GITHUB_BOT_ORG
  if (!org) throw new Error("GITHUB_BOT_ORG is not set")
  return org
}

function client(): Octokit {
  return new Octokit({ auth: botToken() })
}

export async function repoExists(name: string): Promise<boolean> {
  const octokit = client()
  try {
    await octokit.repos.get({ owner: botOrg(), repo: name })
    return true
  } catch (err: unknown) {
    if (typeof err === "object" && err && "status" in err && (err as { status: number }).status === 404) {
      return false
    }
    throw err
  }
}

export async function createStagingRepo(name: string, description?: string): Promise<StagingRepo> {
  const octokit = client()
  const org = botOrg()

  // auto_init: true creates a stub README + initial commit. This is required because
  // GitHub's Git Data API (createBlob etc) refuses with 409 "Git Repository is empty"
  // on a repo with no commits/ref. Our first real commit will be a child of the auto-init.
  const { data } = await octokit.repos.createInOrg({
    org,
    name,
    description: description ?? "Generated by CLICreator",
    private: true,
    auto_init: true,
    has_issues: false,
    has_projects: false,
    has_wiki: false,
  })

  return {
    owner: data.owner.login,
    name: data.name,
    url: data.html_url,
    defaultBranch: data.default_branch ?? "main",
  }
}

// pushInitialCommit pushes the generated source as a single commit on top of the
// auto-init README commit. Sequence: get HEAD → blobs → tree (no base) → commit (parent=HEAD)
// → update ref. The auto-init README is overwritten because we don't include it in the new tree.
export async function pushInitialCommit(
  owner: string,
  repo: string,
  files: Map<string, Buffer>,
  message: string,
  branch: string = "main"
): Promise<string> {
  const octokit = client()

  // 1. Get the auto-init commit SHA — our new commit's parent
  const { data: ref } = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${branch}`,
  })
  const parentSha = ref.object.sha

  // 2. Create a blob for each file
  const blobs = await Promise.all(
    Array.from(files.entries()).map(async ([path, content]) => {
      const { data } = await octokit.git.createBlob({
        owner,
        repo,
        content: content.toString("base64"),
        encoding: "base64",
      })
      return { path, sha: data.sha }
    })
  )

  // 3. Create a tree (no base_tree → fresh tree, drops the auto-init README)
  const { data: tree } = await octokit.git.createTree({
    owner,
    repo,
    tree: blobs.map((b) => ({
      path: b.path,
      mode: "100644",
      type: "blob",
      sha: b.sha,
    })),
  })

  // 4. Create a commit on top of the auto-init commit
  const { data: commit } = await octokit.git.createCommit({
    owner,
    repo,
    message,
    tree: tree.sha,
    parents: [parentSha],
  })

  // 5. Fast-forward the branch to our new commit
  await octokit.git.updateRef({
    owner,
    repo,
    ref: `heads/${branch}`,
    sha: commit.sha,
  })

  return commit.sha
}

// pushCommit creates a new commit on top of an existing parent (the previous build's
// commit). The new tree is fresh — files not in the map are dropped. Returns the new
// commit SHA. Use this for rebuilds; use pushInitialCommit for the very first push.
export async function pushCommit(
  owner: string,
  repo: string,
  files: Map<string, Buffer>,
  parentSha: string,
  message: string,
  branch: string = "main"
): Promise<string> {
  const octokit = client()

  const blobs = await Promise.all(
    Array.from(files.entries()).map(async ([path, content]) => {
      const { data } = await octokit.git.createBlob({
        owner,
        repo,
        content: content.toString("base64"),
        encoding: "base64",
      })
      return { path, sha: data.sha }
    })
  )

  const { data: tree } = await octokit.git.createTree({
    owner,
    repo,
    tree: blobs.map((b) => ({
      path: b.path,
      mode: "100644",
      type: "blob",
      sha: b.sha,
    })),
  })

  const { data: commit } = await octokit.git.createCommit({
    owner,
    repo,
    message,
    tree: tree.sha,
    parents: [parentSha],
  })

  await octokit.git.updateRef({
    owner,
    repo,
    ref: `heads/${branch}`,
    sha: commit.sha,
  })

  return commit.sha
}

export async function inviteCollaborator(
  owner: string,
  repo: string,
  username: string,
  permission: "pull" | "push" | "admin" | "maintain" | "triage" = "push"
): Promise<void> {
  const octokit = client()
  await octokit.repos.addCollaborator({
    owner,
    repo,
    username,
    permission,
  })
}

// validateRepoName enforces GitHub repo name rules: alphanumeric, dot, dash, underscore.
// Max 100 chars, can't start with a dot or dash.
export function validateRepoName(name: string): string | null {
  if (!name) return "Project name is required"
  if (name.length > 100) return "Project name must be 100 characters or fewer"
  if (!/^[a-zA-Z0-9][a-zA-Z0-9._-]*$/.test(name)) {
    return "Project name can only contain letters, numbers, dots, dashes, and underscores"
  }
  return null
}
